### ISSUE TITLE
Couldn't find translation key

### ISSUE THREAD

**Issue by lisandi** [ether/ep_template_content#4]
We receive the following Error Messages in Chrome on Mac OSX with the newest versions of Etherpad (installed yesterday from Github)

Couldn't find translation key ep_template_contents.style
html10n.translateNode @ html10n.js?v=871e115c:1

**Comment by JohnMcLear** [comment]
Yea there is no Locales folder 📦   I will add one real quick

**Comment by JohnMcLear** [comment]
Fixed with https://github.com/ether/ep_template_content/commit/7cca68b2b70af6f86d7c29d697f111c12ef2d58a
